### PR TITLE
Adding Linux build

### PR DESCRIPTION
**Pull request by zeitos**
Hi guys, I couldn't test it since I don't have pro :(

### CODE REVIEW

**Comment by spdermn02** [comment]
Thanks for the PR! I'll run a test when I can but should be fine. I really need to adjust the build process to be scripted and system agnostic at some point. 

I appreciate you

**Comment by zeitos** [comment]
I don't know any tool to help you with that other than coding all those file copies and renames :S  
and it's not that difficult to generate a build for each system. the one thing that might be handy is to integrate the repo to circleci, travis or any other build tool to automatically publish those binaries. .... maybe that's what you were referring to.

**Comment by spdermn02** [comment]
i'm loading up a linux VM and will do some testing, i did shift this to be built from a windows command line as the others are built that way as well. but i appreciate the PR to get this jump started.

I also need to double check the documentation for getting a plugin started for linux, as he changed the start process in the entry.tp which may need to be adjusted as well.

**Comment by spdermn02** [comment]
I'm going to be changing out the build process to work through a script instead will make it more maintainable.  Closing this PR for now. Linux release would be for 4.3.2 release once it's tested.

**Pull request closed without merging**
